version: "3.9"

services:
  svelte_app:
    image: nginx:alpine
    container_name: svelte_prod
    ports:
      - "5173:5173"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped
