import os

UDP_HOST = os.environ.get("UDP_HOST", "127.0.0.1")
RR_IP = os.environ.get("RR_IP", "127.0.0.1")


environment:
  UDP_HOST: host.docker.internal
  RR_IP: host.docker.internal

environment:
  UDP_HOST: 192.168.10.50
  RR_IP: 192.168.10.50
